[
  {
    _id: "1",
    title: "Healthcare Volunteer Program",
    category: "healthcare",
    location: "Dhaka, Bangladesh",
    volunteersNeeded: "15",
    deadline: "2024-12-28",
    description:
      "Join us in a healthcare initiative to provide medical support to underprivileged areas.",
    thumbnail: "https://i.ibb.co/KjsGmvd/3bc1b1e851fef03a6c05eb9984bc0cc6.jpg",
    organizerName: "Md Abu Rayhan",
    organizerEmail: "aburayhan.bpi@gmail.com",
  },
  {
    _id: "2",
    title: "Teaching Program for Underprivileged Kids",
    category: "education",
    location: "Chittagong, Bangladesh",
    volunteersNeeded: "10",
    deadline: "2025-01-15",
    description:
      "Help in educating children from marginalized communities by volunteering in our teaching program.",
    thumbnail: "https://i.ibb.co/9Tqw6cY/2c03b29474186ae7ba0484a0f43d87e5.jpg",
    organizerName: "Sara Jahan",
    organizerEmail: "sara.jahan@example.com",
  },
  {
    _id: "3",
    title: "Animal Rescue and Care Program",
    category: "animal welfare",
    location: "Sylhet, Bangladesh",
    volunteersNeeded: "8",
    deadline: "2024-12-22",
    description:
      "Join our mission to rescue and care for stray animals in the city.",
    thumbnail: "https://i.ibb.co/0QZPfJN/aa3bc19c48614b7b822487634a5ed65a.jpg",
    organizerName: "Mohiuddin Hasan",
    organizerEmail: "mohiuddin.hasan@example.com",
  },
  {
    _id: "4",
    title: "Community Cleanup Campaign",
    category: "social service",
    location: "Rajshahi, Bangladesh",
    volunteersNeeded: "20",
    deadline: "2025-02-10",
    description:
      "Volunteer to clean up local parks and streets in a bid to make the community cleaner and safer.",
    thumbnail: "https://i.ibb.co/wQfcFK9/fd6c84f2e08dba2f5953fb7f5af6a56f.jpg",
    organizerName: "Shahina Begum",
    organizerEmail: "shahina.begum@example.com",
  },
  {
    _id: "5",
    title: "Water Supply Awareness Campaign",
    category: "healthcare",
    location: "Barisal, Bangladesh",
    volunteersNeeded: "12",
    deadline: "2024-12-30",
    description:
      "Raise awareness about clean water and sanitation practices in rural areas.",
    thumbnail: "https://i.ibb.co/rdJ1LP6/bd722a04d0213b0d919bdd2ab7332a57.jpg",
    organizerName: "Rahat Karim",
    organizerEmail: "rahat.karim@example.com",
  },
][
  ({
    _id: "6",
    title: "Disaster Relief Volunteer Team",
    category: "social service",
    location: "Khulna, Bangladesh",
    volunteersNeeded: "50",
    deadline: "2025-03-05",
    description:
      "Join our disaster relief team to provide essential services to those affected by the recent floods.",
    thumbnail: "https://i.ibb.co/FVcvNPp/17717f584979ecfe5bbef5c34ac4634a.jpg",
    organizerName: "Kamrul Islam",
    organizerEmail: "kamrul.islam@example.com",
  },
  {
    _id: "7",
    title: "Blood Donation Drive",
    category: "healthcare",
    location: "Dhaka, Bangladesh",
    volunteersNeeded: "30",
    deadline: "2024-12-25",
    description:
      "Help save lives by volunteering for our blood donation drive, offering support to those in need.",
    thumbnail: "https://i.ibb.co/FVcvNPp/17717f584979ecfe5bbef5c34ac4634a.jpg",
    organizerName: "Ayesha Sultana",
    organizerEmail: "ayesha.sultana@example.com",
  },
  {
    _id: "8",
    title: "Technology Education for Women",
    category: "education",
    location: "Mymensingh, Bangladesh",
    volunteersNeeded: "18",
    deadline: "2025-01-20",
    description:
      "Teach women essential tech skills to empower them and open up new career opportunities.",
    thumbnail: "https://i.ibb.co/TvTCM5w/efda2688382001cd3675eefe64b4681c.jpg",
    organizerName: "Riyad Chowdhury",
    organizerEmail: "riyad.chowdhury@example.com",
  },
  {
    _id: "9",
    title: "Tree Plantation Campaign",
    category: "social service",
    location: "Narayanganj, Bangladesh",
    volunteersNeeded: "25",
    deadline: "2025-01-05",
    description:
      "Join us in planting trees and promoting environmental conservation in urban areas.",
    thumbnail: "https://i.ibb.co/F6KVZ9k/9f32709fdb1f22bd06b93d0772bf7ff4.jpg",
    organizerName: "Salma Khatun",
    organizerEmail: "salma.khatun@example.com",
  },
  {
    _id: "10",
    title: "Animal Shelter Support Program",
    category: "animal welfare",
    location: "Rangpur, Bangladesh",
    volunteersNeeded: "12",
    deadline: "2024-12-18",
    description:
      "Help care for and support rescued animals by volunteering at our shelter.",
    thumbnail: "https://i.ibb.co/MC3qdNZ/9d4159dd9cea7ff85fc30f97631b6889.jpg",
    organizerName: "Fariha Akter",
    organizerEmail: "fariha.akter@example.com",
  },
  {
    _id: "11",
    title: "Elderly Care and Support",
    category: "social service",
    location: "Sylhet, Bangladesh",
    volunteersNeeded: "10",
    deadline: "2025-02-25",
    description:
      "Assist the elderly in local care homes by providing companionship and assistance with daily activities.",
    thumbnail: "https://i.ibb.co/kMtkVVf/7bc161eacec1c846e7743798061d7a0e.jpg",
    organizerName: "Jamil Ahmed",
    organizerEmail: "jamil.ahmed@example.com",
  })
];
